name: text_sns
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_flavor: ^3.1.1
  flutter_flavorizr: ^2.1.6
  firebase_core: ^2.4.1
  cloud_firestore: ^4.7.0
  freezed_annotation: ^2.2.0
  get: ^4.6.5
  fluttertoast: ^8.1.2
  firebase_auth: ^4.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
  flavors:
    dev:
      app:
        name: "テキストSNS Dev"
      android:
        applicationId: "com.firebaseapp.text_sns_dev"
      ios:
        bundleId: "com.firebaseapp.textSnsDev"
    prod:
      app:
        name: "テキストSNS"
      android:
        applicationId: "com.firebaseapp.text_sns_prod"
      ios:
        bundleId: "com.firebaseapp.textSnsProd"
